                        const logchannel = await message.guild.channels.cache.get('CHANNELIDHERE')
                        const logembed = new Discord.MessageEmbed()
                        .setTitle('Demote Action Logged')
                        .setURL(`https://www.roblox.com/users/${robloxid}/profile`)
                        .setThumbnail(`https://www.roblox.com/headshot-thumbnail/image?userid=${robloxid}&width=420&height=420&format=png`)
                        .setColor('GREEN')
                        .addField('__Ranker__', `<@${message.author.id}>`)
                        .addField('__Ranked Username__' , `${robloxname}`)
                        .addField('__Old Rank__' ,  `${sucsess.oldRole.name}`)
                        .addField('__New Rank__' ,  `${sucsess.newRole.name}`)
                        .setFooter('Logging System')
                        .setTimestamp()
                        let loggerembed = await logchannel.send(logembed)
